disabled_rules:
    - trailing_whitespace
    - vertical_parameter_alignment
line_length:
    warning: 120
    error: 160
    ignores_comments: true
    ignores_urls: true
identifier_name:
    excluded:
        - id
        - URL
excluded:
    - Pods
    - Tests
    - Source
